id: AE6466B6D
base_file: f8D68.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-15 20:47:21.433830
  last_modified_at: 2022-06-15 20:47:21.433832
