id: AE6466B6D
base_file: fA144.txt
type: translation
source_metadata:
  languages:
  - en
  - de
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-06-15 20:47:21.449904
  last_modified_at: 2022-06-15 20:47:21.449907
