id: AE6466B6D
base_file: f2B32.txt
type: translation
source_metadata:
  languages:
  - en
  - de
  - pt
  - bo
  datatype: PlainText
  created_at: 2022-06-15 20:47:21.345705
  last_modified_at: 2022-06-15 20:47:21.345711
