id: AE6466B6D
base_file: f7B9D.txt
type: translation
source_metadata:
  languages:
  - en
  - de
  - es
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-06-15 20:47:21.413358
  last_modified_at: 2022-06-15 20:47:21.413361
