id: AE6466B6D
base_file: fBA33.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-15 20:47:21.513843
  last_modified_at: 2022-06-15 20:47:21.513846
