id: AE6466B6D
base_file: fEE37.txt
type: translation
source_metadata:
  languages:
  - en
  - pt
  - zh
  - bo
  datatype: PlainText
  created_at: 2022-06-15 20:47:21.566369
  last_modified_at: 2022-06-15 20:47:21.566371
