id: AE6466B6D
base_file: fF8AA.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-15 20:47:21.572495
  last_modified_at: 2022-06-15 20:47:21.572497
