id: AE6466B6D
base_file: f2D28.txt
type: translation
source_metadata:
  languages:
  - en
  - es
  - fr
  - pt
  - bo
  datatype: PlainText
  created_at: 2022-06-15 20:47:21.352660
  last_modified_at: 2022-06-15 20:47:21.352664
