id: AE6466B6D
base_file: f74D2.txt
type: translation
source_metadata:
  languages:
  - en
  - de
  - es
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-06-15 20:47:21.399278
  last_modified_at: 2022-06-15 20:47:21.399280
