id: AE6466B6D
base_file: f8644.txt
type: translation
source_metadata:
  languages:
  - en
  - de
  - pt
  - zh
  - bo
  datatype: PlainText
  created_at: 2022-06-15 20:47:21.426731
  last_modified_at: 2022-06-15 20:47:21.426734
