id: AE6466B6D
base_file: f24A9.txt
type: translation
source_metadata:
  languages:
  - en
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-06-15 20:47:21.325963
  last_modified_at: 2022-06-15 20:47:21.325968
