id: AE6466B6D
base_file: f799F.txt
type: translation
source_metadata:
  languages:
  - en
  - de
  - es
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-06-15 20:47:21.409873
  last_modified_at: 2022-06-15 20:47:21.409876
