id: AE6466B6D
base_file: fCCC9.txt
type: translation
source_metadata:
  languages:
  - en
  - zh
  - bo
  datatype: PlainText
  created_at: 2022-06-15 20:47:21.533366
  last_modified_at: 2022-06-15 20:47:21.533369
