id: AE6466B6D
base_file: fA80E.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-15 20:47:21.480510
  last_modified_at: 2022-06-15 20:47:21.480513
