id: AE6466B6D
base_file: fA928.txt
type: translation
source_metadata:
  languages:
  - en
  - de
  - fr
  - it
  - bo
  datatype: PlainText
  created_at: 2022-06-15 20:47:21.485879
  last_modified_at: 2022-06-15 20:47:21.485882
