id: AE6466B6D
base_file: fD1AD.txt
type: translation
source_metadata:
  languages:
  - en
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-06-15 20:47:21.540158
  last_modified_at: 2022-06-15 20:47:21.540161
