id: AE6466B6D
base_file: fBB88.txt
type: translation
source_metadata:
  languages:
  - en
  - pt
  - bo
  datatype: PlainText
  created_at: 2022-06-15 20:47:21.515333
  last_modified_at: 2022-06-15 20:47:21.515336
